Repository workflow-engine-project/workflow-engine, pull requests merged in 2024-03, with the labels that each got.

#49 fix : ZRWC-108 : 워크플로우 Update API의 에러를 수정한다.
  workflow_engine/project_apps/api/views.py
Labels: bug

#53 refactor : ZRWC-111 : 워크플로우 API의 serialize 과정을 리팩터링한다.
  workflow_engine/project_apps/api/serializers.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#50 refactor : ZRWC-109 : 스케줄링 DB 모델 is_active 필드 default 옵션 값을 False로 수정한다.
  workflow_engine/project_apps/migrations/0007_alter_scheduling_is_active.py
  workflow_engine/project_apps/models/scheduling.py
Labels: refactor

#51 fix : ZRWC-110 : 스케줄링 Create 로직을 수정한다.
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: bug

#52 feat : ZRWC-107 : 스케줄링 실행 API를 구현한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat

#54 refactor : ZRWC-112 : 워크플로우 Delete API의 실패 시 처리 과정을 리팩터링한다.
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#56 fix : ZRWC-113 : 스케줄링 CRUD API 관련 버그를 수정한다.
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: bug

#58 refactor : ZRWC-118 : Redis host 및 port를 환경변수로 관리한다.
  workflow_engine/project_apps/service/lock_utils.py
  workflow_engine/workflow_engine/settings.py
Labels: refactor

#60 fix : ZRWC-120 : workflow_engine 컨테이너 내부에서 Docker 데몬과 연결되지 않는 문제를 해결한다.
  docker-compose.yml
  requirements.txt
Labels: bug, chore

#61 style : ZRWC-117 : 각 함수, 클래스 및 메서드에 docstring을 추가 및 수정한다.
  workflow_engine/project_apps/api/serializers.py
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/engine/__init__.py
  workflow_engine/project_apps/engine/job_dependency.py
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/engine/job_terminate.py
  workflow_engine/project_apps/engine/scheduling_execute.py
  workflow_engine/project_apps/engine/tasks_manager.py
  workflow_engine/project_apps/repository/history_repository.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
  workflow_engine/project_apps/service/lock_utils.py
  workflow_engine/project_apps/service/scheduling_service.py
  workflow_engine/project_apps/service/workflow_manage.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: style

#62 fix : ZRWC-121 : 스케줄링 Create API에서 워크플로우 uuid의 존재여부를 확인하지 않고 스케줄링을 생성하는 문제를 수정한다.
  workflow_engine/project_apps/repository/scheduling_repository.py
Labels: bug

#63 fix : ZRWC-122 : 의존성이 걸린 작업의 실존 여부를 검사하는 로직을 추가한다.
  workflow_engine/project_apps/service/workflow_service.py
Labels: bug

#66 feat : ZRWC-114 : 스케줄링 serializer 로직을 구현한다.
  workflow_engine/project_apps/service/scheduling_service.py
Labels: refactor

#65 refactor : ZRWC-124 : 데이터베이스 HOST값 설정을 env 파일의 POSTGRESQL_HOST 변수를 사용하여 설정한다.
  workflow_engine/workflow_engine/settings.py
Labels: refactor

#67 feat: ZRWC-125 : 스케줄링 리스트 Read API 를 구현한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat

#68 refactor : ZRWC-127 : CRUD API 관련 리팩토링을 진행한다.
  workflow_engine/project_apps/api/serializers.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#70 fix : ZRWC-123 : job의 next_job_names 값이 변경 됨에 따라 의존관계를 맺고 있는 job의 depends_count가 자동으로 변경되도록 수정한다.
  workflow_engine/project_apps/service/workflow_service.py
Labels: bug

#71 feat : ZRWC-128 : 스케줄링이 활성화 상태이면 업데이트가 되지 않도록 구현한다.
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat

#72 feat : ZRWC-129 : 실행중인 스케줄링을 임의로 비활성화 상태로 변경할 수 있는 로직을 구현한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/engine/scheduling_execute.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat, refactor

#74 refactor : ZRWC-131 : 워크플로우 업데이트 로직 리팩토링을 진행한다.
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#76 docs : ZRWC-136 : README.md를 수정한다.
  README.md
Labels: docs

#77 fix : ZRWC-135 : 워크플로우 실행로직에서 워크플로우의 상태에 따라 다른 반환 값을 제공하도록 수정한다.
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/service/workflow_manage.py
Labels: bug

#78 refactor : ZRWC-137 : 워크플로우 종료(성공/실패)시 터미널에 종료 메세지를 출력한다.
  workflow_engine/project_apps/service/workflow_manage.py
Labels: refactor

#79 docs : ZRWC-136 : README.md를 수정한다.
  README.md
Labels: docs

#81 docs : ZRWC-136 : README.md를 수정한다.
  README.md
Labels: docs

#82 chore : ZRWC-132 : drf-yasg 라이브러리 requirements.txt에 추가한다.
  requirements.txt
Labels: chore
