Repository workflow-engine-project/workflow-engine, pull requests merged in 2024-02, with the labels that each got.

#14 feat : ZRWC-55 : 워크플로우 Delete API 로직 구현
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: chore, feat

#17 feat: ZRWC-66 : Job 의존성 관련 알고리즘 구현
  workflow_engine/dump.rdb
  workflow_engine/project_apps/engine/__init__.py
  workflow_engine/project_apps/engine/job_dependency.py
  workflow_engine/workflow_engine/celery.py
Labels: feat

#15 feat : ZRWC-54 : 워크플로우 Update API 구현
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
  workflow_engine/project_apps/service/workflow_service.py
  workflow_engine/workflow_engine/settings.py
Labels: feat

#16 feat : ZRWC-53 : 워크플로우 Read API 구현
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: feat

#18 feat : ZRWC-67 : job을 실제 수행하는 로직 구현
  workflow_engine/project_apps/constants.py
  workflow_engine/project_apps/engine/__init__.py
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/repository/history_repository.py
  workflow_engine/project_apps/service/workflow_service.py
  workflow_engine/workflow_engine/celery.py
Labels: chore, feat

#19 refactor : ZRWC-66 : job_dependency 파일에 job_execute 함수 import 구문 추가
  workflow_engine/project_apps/engine/job_dependency.py
Labels: refactor

#20 refactor : ZRWC-65 : workflow 실행 과정 리팩터링
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#21 refactor : ZRWC-53 : WorflowRepository 및 JobRepository의 get 메서드에 exception handling 구문 추가
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
Labels: refactor

#22 refactor : ZRWC-54 : WorflowRepository 및 JobRepository의 update 메서드에 exception handling 구문 추가
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/repository/workflow_repository.py
Labels: refactor

#23 fix: ZRWC-67 : constants.py 에 JOB_STATUS_WAITING 추가
  workflow_engine/project_apps/constants.py
Labels: bug

#24 fix : ZRWC-85 : MVP1 리팩토링 전 발생한 버그 수정
  workflow_engine/project_apps/migrations/0003_alter_history_completed_at_alter_history_started_at_and_more.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: bug, chore

#26 refactor : ZRWC-87 : update_history_status 메소드 리팩토링
  workflow_engine/project_apps/repository/history_repository.py
Labels: refactor

#28 refactor : ZRWC-88 : job을 실행하는 로직과 job 의존성 관련 로직을 분리
  workflow_engine/project_apps/engine/job_dependency.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#27 refactor : ZRWC-89 : update_workflow 메소드에 transaction.atomic 데코레이터 추가
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#25 refactor : ZRWC-71 : 순환 임포트 문제 해결
  workflow_engine/project_apps/engine/job_dependency.py
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/engine/tasks_manager.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#29 refactor : ZRWC-71 : 순환 임포트 문제 최종 해결 및 모듈 임프트 경로 수정
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/service/workflow_manage.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#32 refactor : ZRWC-92 : 워크플로우 CRUD API 뷰 클래스를 하나로 통합한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
Labels: refactor

#31 refactor : ZRWC-91 : 워크플로우 Delete API 요청 시에 발생하는 에러를 수정한다.
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#30 feat : ZRWC-79 : 컨테이너 내부의 환경변수 적용 구현
  workflow_engine/project_apps/engine/job_execute.py
Labels: feat

#34 refactor : ZRWC-90 : Lock 관련 기능을 threading에서 Redis lock으로 수정
  workflow_engine/project_apps/service/lock_utils.py
  workflow_engine/project_apps/service/workflow_manage.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: refactor

#43 fix : ZRWC-104 : Job 테이블의 next_job_names 필드를 JSON으로 파싱하는 에러를 수정한다.
  workflow_engine/project_apps/service/workflow_manage.py
Labels: feat

#41 feat : ZRWC-86 : job task가 실패처리되었을 경우 해당 워크플로우의 실행중인 job task들도 모두 종료하는 로직 추가 구현
  workflow_engine/project_apps/constants.py
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/engine/job_terminate.py
  workflow_engine/project_apps/service/workflow_manage.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: feat, refactor

#37 feat : ZRWC-94 : 스케줄링 Create API를 구현한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat

#36 feat : ZRWC-93 : 스케줄링 DB를 확정한다.
  workflow_engine/project_apps/migrations/0004_scheduling.py
  workflow_engine/project_apps/models/__init__.py
  workflow_engine/project_apps/models/scheduling.py
Labels: feat

#39 feat : ZRWC-96 : 스케줄링 Update API를 구현한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat

#40 feat : ZRWC-97 : 스케줄링 Delete API를 구현한다.
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat

#38 feat : ZRWC-95 : 스케줄링 Read API를 구현한다.
  workflow_engine/project_apps/api/urls.py
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: feat, refactor

#46 refactor : ZRWC-105 : 스케줄링 DB 모델을 수정한다.
  workflow_engine/project_apps/migrations/0005_scheduling_repeat_count_alter_scheduling_interval_and_more.py
  workflow_engine/project_apps/models/scheduling.py
Labels: refactor

#47 refactor : ZRWC-106 : 수정된 스케줄링 DB 관련 CRUD API 리팩토링 작업을 진행한다.
  workflow_engine/project_apps/api/views.py
  workflow_engine/project_apps/repository/scheduling_repository.py
  workflow_engine/project_apps/service/scheduling_service.py
Labels: refactor

#48 feat : ZRWC-81 : timeout과 retries를 적용하여 job을 수행하도록 로직 및 모델 칼럼 추가
  workflow_engine/project_apps/api/serializers.py
  workflow_engine/project_apps/engine/job_dependency.py
  workflow_engine/project_apps/engine/job_execute.py
  workflow_engine/project_apps/engine/tasks_manager.py
  workflow_engine/project_apps/migrations/0006_job_retries_job_timeout.py
  workflow_engine/project_apps/models/job.py
  workflow_engine/project_apps/repository/job_repository.py
  workflow_engine/project_apps/service/workflow_manage.py
  workflow_engine/project_apps/service/workflow_service.py
Labels: feat
